language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- stable
- 6
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- export CHROME_BIN=chromium-browser
- sh -e /etc/init.d/xvfb start
- sleep 3
notifications:
  email: false
